# Generated by Django 6.0.1 on 2026-04-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
